name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup-flutter
      uses: subosito/flutter-action@v1.3.2
      with: 
        flutter-version: '1.17.3'
        channel: 'dev'
    - run: flutter pub get
    - run: flutter  analyze
    - run: flutter test --coverage
