name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup-flutter
      uses: subosito/flutter-action@v1.3.2
      with: 
        flutter-version: '1.12.14'
        channel: 'dev'
    - run: flutter upgrade        
    - run: flutter pub get
    - run: flutter pub upgrade
    - run: flutter analyze
    - run:  flutter build apk --split-per-abi
    - run: flutter test --coverage
